version: 2
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/"
      - "/packages/zeta-app-contracts"
      - "/packages/zevm-app-contracts"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependabot: " 
    labels:
      - "dependencies" 
    allow:
      - dependency-name: "@zetachain/addresses"
      - dependency-name: "@zetachain/toolkit"
      - dependency-name: "@zetachain/ui-toolkit
