export const globalLinks = {
  discordLink: "https://discord.gg/zetachain",
  twitterLink: "https://twitter.com/zetablockchain",
  telegramLink: "https://t.me/zetachainofficial",
  blogUrl: "https://zetachain.com/blog",
  marketingSiteUrl: "https://zetachain.com",
  explorerUrl: "https://zetascan.com",
  labsLink: "https://labs.zetachain.com",
  privacyLink: "https://zetachain.com/privacy",
  termsOfUseLink: "https://zetachain.com/terms-of-use",
  githubLink: "https://github.com/zeta-chain",
  whitepaperLink: "https://www.zetachain.com/whitepaper.pdf",
  mediumLink: "https://blog.zetachain.com/",
  youTubeLink: "https://www.youtube.com/@ZetaBlockchain",
  redditLink: "https://www.reddit.com/r/zetablockchain",
  supportEmailLink: "mailto:support@zetachain.com",
  publicIssueTracker: "https://github.com/zeta-chain/issues",
  bugBountyLink: "/about/info/bug-bounty",
  communityAmbassadorLink: "https://zealy.io/cw/zetachain/questboard",
  workWithUsLink: "https://www.zetachain.com/careers",
};
