export const globalLinks = {
  discordLink: "https://discord.gg/zetachain",
  twitterLink: "https://twitter.com/zetablockchain",
  telegramLink: "https://t.me/zetachainofficial",
  blogUrl: "https://zetachain.com/blog",
  marketingSiteUrl: "https://zetachain.com",
  explorerUrl: "https://explorer.zetachain.com",
  labsLink: "https://labs.zetachain.com",
  privacyLink: "https://zetachain.com/privacy",
  termsOfUseLink: "https://zetachain.com/terms-of-use",
  githubLink: "https://github.com/zeta-chain",
  whitepaperLink: "https://www.zetachain.com/whitepaper.pdf",
  mediumLink: "https://blog.zetachain.com/",
  youTubeLink: "https://www.youtube.com/@ZetaBlockchain",
  redditLink: "https://www.reddit.com/r/zetablockchain",
  supportEmailLink: "mailto:support@zetachain.com",
  bugBountyLink: "https://hackenproof.com/zetachain",
  techAmbassadorProgramLink: "https://zetachain.deform.cc/TechAmbassadors",
  communityAmbassadorLink: "https://zealy.io/cw/zetachain/questboard",
  workWithUsLink: "https://zetachain.notion.site/Work-With-ZetaChain-5023467bea594d9c83e54e81a1afa97b",
};
