name: Update CLI docs

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *" # scheduled to run every day at midnight
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout protocol-contracts repository
        uses: actions/checkout@v2
        with:
          repository: zeta-chain/cli
          path: cli

      - name: Update docs
        run: |
          mkdir -p src/pages/reference/
          rm src/pages/reference/cli.mdx
          cp -r cli/docs/index.md src/pages/reference/cli.mdx
          rm -rf cli

      - name: Check for changes
        id: check-changes
        run: |
          git add src/pages/reference/
          git diff --cached --exit-code || echo "::set-output name=changed::true"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "docs: update CLI docs"
          body: |
            This PR contains updates to CLI docs
            from the `zeta-chain/cli` repository.
          commit-message: |
            "docs: update CLI docs from zeta-chain/cli"
          base: main
          branch: docs/updates-from-zeta-chain-cli
        if: steps.check-changes.outputs.changed == 'true'
