name: Update protocol-contract-ton docs

on:
  schedule:
    - cron: "0 0 * * *" # scheduled to run every day at midnight
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout zeta-chain/protocol-contracts-ton repository
        uses: actions/checkout@v2
        with:
          repository: zeta-chain/protocol-contracts-ton
          path: protocol-contracts-ton

      - name: Update docs
        run: |
          mkdir -p src/pages/developers/protocol/
          rm -f src/pages/developers/protocol/ton.mdx
          cp protocol-contracts-ton/docs/gateway.md src/pages/developers/protocol/ton.mdx
          rm -rf protocol-contracts-ton

      - name: Check for changes
        id: check-changes
        run: |
          git add src/pages/developers/protocol
          git diff --cached --exit-code || echo "::set-output name=changed::true"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "docs: update protocol-contract-ton docs"
          body: |
            This PR contains updates to the protocol-contract-ton docs.
          commit-message: |
            "docs: update protocol-contract-ton docs"
          base: main
          branch: docs/updates-from-protocol-contracts-ton
        if: steps.check-changes.outputs.changed == 'true'
