name: Update protocol-contract-solana docs

on:
  schedule:
    - cron: "0 0 * * *" # scheduled to run every day at midnight
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout zeta-chain/protocol-contracts-solana repository
        uses: actions/checkout@v2
        with:
          repository: zeta-chain/protocol-contracts-solana
          path: protocol-contracts-solana

      - name: Update docs
        run: |
          mkdir -p src/pages/developers/protocol/
          rm -f src/pages/developers/protocol/solana.md
          cp protocol-contracts-solana/docs/gateway.md src/pages/developers/protocol/solana.md
          rm -rf protocol-contracts-solana

      - name: Check for changes
        id: check-changes
        run: |
          git add src/pages/developers/protocol
          git diff --cached --exit-code || echo "::set-output name=changed::true"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "docs(solana): update protocol contracts"
          body: |
            This PR syncs the docs with protocol-contracts-solana
          commit-message: |
            "docs: update protocol-contract-solana docs"
          base: main
          branch: docs/updates-from-protocol-contracts-solana
        if: steps.check-changes.outputs.changed == 'true'
